"""Fills the S-89-S PDF template (AcroForm) with an assignment's data.

Field mapping verified empirically against a real PDF generated by BulkPDF
(26-08 agosto/16 Miguel López Pop.pdf):

    900_1_Text_SanSerif  -> Name
    900_2_Text_SanSerif  -> Helper (empty if none)
    900_3_Text_SanSerif  -> Date, "D de MMMM de AAAA" format
    900_4_Text_SanSerif  -> "{number}. {part}"
    900_5_CheckBox       -> Main room
    900_6_CheckBox       -> Overflow room #1
    900_7_CheckBox       -> Overflow room #2
"""
from __future__ import annotations

from pathlib import Path

from pypdf import PdfReader, PdfWriter

from .dates import long_date
from .models import Assignment

_ROOM_FIELD = {
    "principal": "900_5_CheckBox",
    "aux1": "900_6_CheckBox",
    "aux2": "900_7_CheckBox",
}


def fill_pdf(template: Path, assignment: Assignment, destination: Path) -> None:
    reader = PdfReader(str(template))
    writer = PdfWriter()
    writer.append(reader)

    values = {
        "900_1_Text_SanSerif": assignment.name,
        "900_2_Text_SanSerif": assignment.helper or "",
        "900_3_Text_SanSerif": long_date(assignment.date),
        "900_4_Text_SanSerif": f"{assignment.number}. {assignment.part}",
        "900_5_CheckBox": "/Off",
        "900_6_CheckBox": "/Off",
        "900_7_CheckBox": "/Off",
    }
    values[_ROOM_FIELD[assignment.room]] = "/Yes"

    writer.update_page_form_field_values(writer.pages[0], values, auto_regenerate=False)

    destination.parent.mkdir(parents=True, exist_ok=True)
    with open(destination, "wb") as f:
        writer.write(f)
