"""Sends the VMC participation reminder over WhatsApp Web: every
participant in the week gets sent the same photo (that week's program
crop, generated by reminder_workbook.crop_week_jpg) along with a
personalized message with their name, their part, and when it is.

whatsapp_send.py itself is never touched: its low-level pieces (opening
a session, attaching a file with a caption) are reused here by import,
but the send loop is its own because there's no .ics or individual slip
here — it's a single image shared by every recipient of the week.
"""
from __future__ import annotations

from datetime import date, timedelta
from pathlib import Path
from typing import Callable

from playwright.sync_api import sync_playwright

from . import i18n
from .config import TimingConfig, load_config
from .dates import long_date, weekday_name
from .i18n import t
from .reminder_workbook import Participant
from .whatsapp_send import (
    _attach_file,
    _wait_for_chat_ready,
    open_session,
    load_message_template,
)

ProgressCallback = Callable[[str, int, int], None]
ResultCallback = Callable[[Participant, bool, str], None]


def relative_date(target_date: date, today: date | None = None) -> str:
    """"Mañana"/"pasado mañana" ("tomorrow"/"day after tomorrow") are
    always by day count — there's no possible ambiguity there. Beyond
    that, instead of a fixed day range (which can be misleading: "el
    jueves" sounds like this week even if it's actually next week), the
    date's calendar week (Monday-Sunday) is compared against today's: if
    it falls in the same week the day name is used ("el jueves"), if it
    falls in the next one it just says "la semana que viene" ("next
    week") with no more precision, and if it's further out the full date
    is used. Same wording, in whichever language the UI is currently in
    (see dates.py)."""
    en = i18n.current_language() == "en"
    today = today or date.today()
    days = (target_date - today).days
    if days == 0:
        return "today" if en else "hoy"
    if days == 1:
        return "tomorrow" if en else "mañana"
    if days == 2:
        return "the day after tomorrow" if en else "pasado mañana"
    if days < 0:
        return f"on {long_date(target_date)}" if en else f"el {long_date(target_date)}"

    monday_today = today - timedelta(days=today.weekday())
    monday_target = target_date - timedelta(days=target_date.weekday())
    week_difference = (monday_target - monday_today).days // 7

    if week_difference == 0:
        return f"this {weekday_name(target_date.weekday())}" if en else f"el {weekday_name(target_date.weekday())}"
    if week_difference == 1:
        return "next week" if en else "la semana que viene"
    return f"on {long_date(target_date)}" if en else f"el {long_date(target_date)}"


def format_reminder_message(participant: Participant, template: str, today: date | None = None) -> str:
    # This dict's keys are the {placeholders} the user types by hand into
    # their reminder_message.txt (see README) — external, persisted
    # format, not Python identifiers. Both a Spanish and an English name
    # are provided for each one (same pattern as config.py's legacy-key
    # migration) so an existing Spanish template keeps working untouched
    # AND an English-language congregation can write their own template
    # using English placeholder names — neither is "the real one", the
    # congregation picks whichever language they write their message in.
    first_name = participant.name.split()[0]
    role = " y ".join(participant.roles)
    date_str = long_date(participant.date)
    rel_date = relative_date(participant.date, today)
    fields = {
        "nombre": participant.name, "name": participant.name,
        "nombre_pila": first_name, "first_name": first_name,
        "rol": role, "role": role,
        "fecha": date_str, "date": date_str,
        "fecha_relativa": rel_date, "relative_date": rel_date,
    }
    return template.format(**fields)


def send_reminders(
    items: list[tuple[Participant, Path]],
    plantilla_mensaje: Path,
    tiempos: TimingConfig | None = None,
    on_progreso: ProgressCallback | None = None,
    on_resultado: ResultCallback | None = None,
    debe_cancelar: Callable[[], bool] | None = None,
    on_esperando_qr: Callable[[], None] | None = None,
) -> None:
    """items: list of (participant_with_phone, week_jpg_path) — normally
    the same jpg path repeated for everyone, since it's the crop of the
    whole week, the same for any recipient.

    Same retry/session-reopen pattern as
    whatsapp_send.send_assignments, simplified: a single image with a
    caption per send, no .ics.
    """
    import time

    tiempos = tiempos or load_config().timing
    template = load_message_template(plantilla_mensaje)
    total = len(items)

    with sync_playwright() as p:
        context, page = open_session(p, on_esperando_qr=on_esperando_qr)

        for i, (participant, jpg) in enumerate(items, start=1):
            if debe_cancelar and debe_cancelar():
                print(t("envio.cancelado_usuario"))
                break

            print(t("envio.enviando_a", nombre=participant.name, telefono=participant.phone))
            final_error: Exception | None = None
            for attempt in (1, 2):
                if page.is_closed():
                    print(t("envio.navegador_reabriendo"))
                    context, page = open_session(p, on_esperando_qr=on_esperando_qr)
                try:
                    text = format_reminder_message(participant, template)
                    page.goto(f"https://web.whatsapp.com/send?phone={participant.phone}")
                    _wait_for_chat_ready(page, tiempos)
                    _attach_file(page, jpg, tiempos, es_imagen=True, leyenda=text)
                    final_error = None
                    break
                except Exception as e:
                    final_error = e
                    if attempt == 1 and page.is_closed():
                        continue
                    break

            if final_error is not None:
                print(t("envio.aviso_fallo", nombre=participant.name, error=final_error))
                if on_progreso:
                    on_progreso(f"{participant.name} (falló, se omite)", i, total)
                if on_resultado:
                    on_resultado(participant, False, str(final_error))
                continue

            print(t("envio.ok", nombre=participant.name))
            if on_progreso:
                on_progreso(participant.name, i, total)
            if on_resultado:
                on_resultado(participant, True, "")
            time.sleep(tiempos.between_contacts_pause_s)

        context.close()
